

-- ========================================
-- 1. JOBS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE JOBS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME_TH VARCHAR2(100) NOT NULL,
       NAME_EN VARCHAR2(100)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 2. Countrys
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE COUNTRIES (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME_TH VARCHAR2(100) NOT NULL,
       NAME_EN VARCHAR2(100)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 3. Cities
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE CITIES (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME_TH VARCHAR2(100) NOT NULL,
       NAME_EN VARCHAR2(100),
       COUNTRY_ID NUMBER NOT NULL,
       CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 4. USERS
-- ========================================
-- M = Male, F = Female, U = Unknown, N = Not Applicable
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE USERS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       FIRST_NAME VARCHAR2(100) NOT NULL,
       LAST_NAME VARCHAR2(100) NOT NULL,
       EMAIL VARCHAR2(150) NOT NULL,
       PASSWORD VARCHAR2(255) NOT NULL,
       DATE_OF_BIRTH DATE ,
       GENDER CHAR(1) DEFAULT ''N'' CHECK (ROLE IN (''M'', ''F'', ''U'', ''N'')),
       ROLE VARCHAR2(12) DEFAULT ''GENERAL_USER'' CHECK (ROLE IN (''GENERAL_USER'', ''ADMIN'')),
       PHONE VARCHAR2(10),
       JOB_ID NUMBER,
       ADDRESS VARCHAR2(200),
       COUNTRIES_ID NUMBER,
       CITIES_ID NUMBER,
       POST_CODE VARCHAR2(10),
       IMG_PATH_PROF VARCHAR2(150),
       STATUS VARCHAR2(8) DEFAULT ''ACTIVE'' CHECK (STATUS IN (''ACTIVE'', ''INACTIVE'')),
       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
       UPDATED_AT TIMESTAMP,
       CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
       CONSTRAINT FK_USERS_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID),
       CONSTRAINT FK_USERS_COUNTRIES FOREIGN KEY (COUNTRIES_ID) REFERENCES COUNTRIES(ID),
       CONSTRAINT FK_USERS_CITIES FOREIGN KEY (CITIES_ID) REFERENCES CITIES(ID)
   )';
EXCEPTION 
   WHEN OTHERS THEN NULL; 
END;
/
COMMIT;

-- ========================================
-- 5. EVENT TYPES
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE EVENT_TYPES (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME VARCHAR2(100) NOT NULL UNIQUE,
       DESCRIPTION VARCHAR2(200)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 6. EVENTS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE EVENTS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME VARCHAR2(100) NOT NULL,
       DESCRIPTION CLOB NOT NULL,
       TYPE_ID NUMBER NOT NULL,
       LOCATION VARCHAR2(200) NOT NULL,
       HOST_ORGANISATION VARCHAR2(100),
       CREATED_BY NUMBER NOT NULL,
       CONTACT_LINE VARCHAR2(100),
       CONTACT_EMAIL VARCHAR2(150),
       CONTACT_FACEBOOK VARCHAR2(150),
       CONTACT_PHONE CHAR(10),
       START_DATE TIMESTAMP NOT NULL,
       END_DATE TIMESTAMP NOT NULL,
       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
       UPDATED_AT TIMESTAMP ,
       CONSTRAINT FK_EVENTS_TYPE FOREIGN KEY (TYPE_ID) REFERENCES EVENT_TYPES(ID),
       CONSTRAINT FK_EVENTS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- add STATUS ===================================
ALTER TABLE EVENTS
ADD STATUS VARCHAR2(10)
    DEFAULT 'UPCOMING'
    NOT NULL
    CONSTRAINT CHK_EVENTS_STATUS
    CHECK (STATUS IN ('UPCOMING', 'ONGOING', 'FINISHED', 'DELETED'));
    
-- ========================================
-- 13. EVENT_REWARDS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE EVENT_REWARD (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME VARCHAR2(100),
       DESCRIPTION VARCHAR2(150),
       EVENT_ID NUMBER NOT NULL,
       REQUIREMENT_TYPE VARCHAR2(20) DEFAULT ''FREE'' 
           CHECK (REQUIREMENT_TYPE IN (''FREE'', ''CHECKED_IN'', ''PRE_SURVEY_DONE'', ''POST_SURVEY_DONE'')),
       START_REDEEM_AT  TIMESTAMP,
       END_REDEEM_AT    TIMESTAMP,
       QUANTITY NUMBER DEFAULT 0,
       STATUS VARCHAR2(15) DEFAULT ''ACTIVE'' 
           CHECK (STATUS IN (''ACTIVE'', ''INACTIVE'', ''OUT_OF_STOCK'')),
       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
       UPDATED_AT TIMESTAMP,
       CONSTRAINT FK_EVENT_REWARD_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
   )';
EXCEPTION 
   WHEN OTHERS THEN 
      DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
COMMIT;




-- ========================================
-- 14. USER_REWARDS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE USER_REWARDS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       USER_ID NUMBER NOT NULL,
       EVENT_REWARD_ID NUMBER NOT NULL,
       REDEEMED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
       CONSTRAINT FK_USER_REWARD_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
       CONSTRAINT FK_USER_REWARD_REWARD FOREIGN KEY (EVENT_REWARD_ID) REFERENCES EVENT_REWARD(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;


-- ========================================
-- 7. IMAGES_CATEGORY
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE IMAGES_CATEGORY (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME VARCHAR2(100) NOT NULL,
       DESCRIPTION VARCHAR2(200)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 8. IMAGES
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE IMAGES (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       EVENT_ID NUMBER NOT NULL,
       IMG_PATH_EV VARCHAR2(150),
       CATEGORY_ID NUMBER NOT NULL,
       UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
       CONSTRAINT FK_IMAGES_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES IMAGES_CATEGORY(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

--ALTER TABLE IMAGES 
--ADD REWARD_ID NUMBER;
--
--ALTER TABLE IMAGES
--ADD CONSTRAINT FK_IMAGES_REWARD 
--FOREIGN KEY (REWARD_ID) REFERENCES EVENT_REWARD(ID);
--
--COMMIT;
-- ========================================
-- 9. User_Event
-- ========================================
BEGIN
   EXECUTE IMMEDIATE '
       CREATE TABLE USER_EVENTS (
           ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
           USER_ID NUMBER NOT NULL,
           EVENT_ID NUMBER NOT NULL,
           EVENT_ROLE VARCHAR2(9) DEFAULT ''VISITOR'' CHECK (EVENT_ROLE IN (''ORGANIZER'', ''VISITOR'', ''STAFF'', ''EXHIBITOR'')),
           STATUS VARCHAR2(12) DEFAULT ''REGISTRATION'' CHECK (STATUS IN (''REGISTRATION'', ''CHECK_IN'')),
           IMG_PATH_QR VARCHAR2(150),
           PRE_SURVEY_POINT NUMBER,
           POST_SURVEY_POINT NUMBER,
           REGISTRATION_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
           CHECK_IN_AT TIMESTAMP ,
           CONSTRAINT FK_MEMBER_EVENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
           CONSTRAINT FK_MEMBER_EVENTS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
       )
   ';
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
COMMIT;

ALTER TABLE USER_EVENTS
ADD (
    DONE_PRE_SURVEY  NUMBER(1) DEFAULT 0 NOT NULL,
    DONE_POST_SURVEY NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT CHK_PRE_SURVEY CHECK (DONE_PRE_SURVEY IN (0, 1)),
    CONSTRAINT CHK_POST_SURVEY CHECK (DONE_POST_SURVEY IN (0, 1))
);
COMMIT;

-- add sendEmail  ===================================
ALTER TABLE USER_EVENTS
ADD SENDEMAIL NUMBER(1) DEFAULT 0 NOT NULL;

COMMIT;



ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';

--ALTER TABLE USER_EVENTS DROP CONSTRAINT SYS_C008273;
--UPDATE USER_EVENTS 
--SET EVENT_ROLE = 'EXHIBITOR' 
--WHERE EVENT_ROLE = 'EXBIHITOR';

COMMIT;
-- ========================================
-- 10. SURVEYS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE SURVEYS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       NAME VARCHAR2(100) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       EVENT_ID NUMBER NOT NULL,
       POINTS NUMBER DEFAULT 0,
       STATUS VARCHAR2(10) DEFAULT ''ACTIVE'' CHECK (STATUS IN (''ACTIVE'', ''INACTIVE'', ''DELETED'')),
       SURVEYS_TYPE VARCHAR2(12) DEFAULT ''PRE_VISITOR'' CHECK (SURVEYS_TYPE IN (''PRE_VISITOR'', ''POST_VISITOR'', ''PRE_EXHIBITOR'', ''POST_EXHIBITOR'')),
       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
       UPDATED_AT TIMESTAMP ,
       CONSTRAINT FK_SURVEYS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 11. QUESTIONS
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE QUESTIONS (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       SURVEY_ID NUMBER NOT NULL,
       QUESTION VARCHAR2(200) ,
       ANSWER_1 VARCHAR2(100) ,
       ANSWER_2 VARCHAR2(100) ,
       ANSWER_3 VARCHAR2(100) ,
       ANSWER_4 VARCHAR2(100),
       ANSWER_5 VARCHAR2(100),
       QUESTION_TYPE VARCHAR2(11) CHECK (QUESTION_TYPE IN (''SINGLE'', ''MULTIPLE'', ''TEXT'')),
       
       CONSTRAINT FK_QUESTIONS_SURVEY FOREIGN KEY (SURVEY_ID) REFERENCES SURVEYS(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;

-- ========================================
-- 12. RESPONSE_ANSWER
-- ========================================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE RESPONSE_ANSWER (
       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       USER_EVENT_ID NUMBER NOT NULL,
       QUESTION_ID NUMBER NOT NULL,
       ANSWER VARCHAR2(200),
       QUESTION_TYPE VARCHAR2(11) CHECK (QUESTION_TYPE IN (''SINGLE'', ''MULTIPLE'', ''TEXT'')),
       CONSTRAINT FK_USER_EVENT FOREIGN KEY (USER_EVENT_ID) REFERENCES USER_EVENTS(ID),
       CONSTRAINT FK_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
   )';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;


--CREATE TABLE survey_tokens (
--    token VARCHAR2(36) PRIMARY KEY,
--    user_id NUMBER NOT NULL,
--    event_id NUMBER NOT NULL,
--    expiry_date TIMESTAMP,
--    is_used NUMBER(1) DEFAULT 0, -- Oracle ไม่มี BOOLEAN ตรงๆ ใช้ 0 (false) และ 1 (true)
--    
--    -- Foreign Key เชื่อมไปยังตารางหลัก (ตรวจสอบชื่อตารางและชื่อ Column ID ของคุณอีกครั้ง)
--    CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users(id),
--    CONSTRAINT fk_token_event FOREIGN KEY (event_id) REFERENCES events(id),
--    
--    -- Check Constraint เพื่อคุมให้ค่าเป็นแค่ 0 หรือ 1 เท่านั้น
--    CONSTRAINT chk_is_used CHECK (is_used IN (0, 1))
--);
--COMMIT;
SELECT column_name 
FROM user_tab_columns 
WHERE table_name = 'USER_EVENTS';

ALTER TABLE USER_EVENTS DROP COLUMN PRE_SURVEY_POINT CASCADE CONSTRAINTS;
ALTER TABLE USER_EVENTS DROP COLUMN POST_SURVEY_POINT CASCADE CONSTRAINTS;

SELECT
    u.id            AS user_id,
    u.first_name,
    u.last_name,
    e.id            AS event_id,
    e.name          AS event_name,
    ue.event_role,
    ue.status
FROM user_events ue
JOIN users u   ON ue.user_id = u.id
JOIN events e  ON ue.event_id = e.id;

select * from events;


SELECT constraint_name, search_condition
FROM user_constraints
WHERE table_name = 'QUESTIONS'
  AND constraint_type = 'C';


ALTER TABLE USERS
DROP CONSTRAINT SYS_C008237;

ALTER TABLE USERS
ADD CONSTRAINT CK_USERS_ROLE
CHECK (ROLE IN ('GENERAL_USER', 'ADMIN', 'ORGANIZER'));

commit;
